import { Auth } from 'ahmad/components';
import React from 'react';
import { parseCookies } from 'nookies';
import Head from 'next/head';

const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Login King</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/king.svg" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
      </Head>
      <Auth />
    </>
  );
};

export default LoginPage;

export async function getServerSideProps(context) {
  const { token, role } = parseCookies(context);
  if (token) {
    return {
      redirect: {
        destination: `/${role === 'admin' ? '/admin' : '/'}`,
        permanent: true,
      },
    };
  }
  return {
    props: {},
  };
}
