import Head from 'next/head';
import React from 'react';
import Sidebar from '../Sidebar';

const RootLayout = ({ child }) => {
  return (
    <>
      <Head>
        <title> Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <Sidebar children={child} />
    </>
  );
};

export default RootLayout;
