import Head from 'next/head';
import { Auth } from 'ahmad/components';
import { parseCookies } from 'nookies';

export default function Home() {
  return (
    <>
      <Head>
        <title>Website Admin Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
      </Head>
      <div>
        <Auth />
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const { token } = parseCookies(context);
  if (token) {
    return {
      redirect: {
        destination: '/admin',
        permanent: true,
      },
    };
  }
  return {
    props: {},
  };
}
