import Head from 'next/head';
import { About, Auth, Facility, Footer, Header, Hero, Navbar } from 'ahmad/components';
import { parseCookies } from 'nookies';
import User from './user';
import Image from 'next/image';
import { LoginModal } from 'ahmad/components/Modal';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home King Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/king.svg" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
      </Head>

      <main>
        <Navbar />
        <Header />
        {/* <LoginModal /> */}
        <Hero />
        <Facility />
        <About />
        <Footer />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { token, role } = parseCookies(context);
  if ((role === 'resepsionis' || role === 'admin') && token) {
    return {
      redirect: {
        destination: '/admin',
        permanent: true,
      },
    };
  }
  return {
    props: {},
  };
}
